### ISSUE TITLE
Provide a list of missing parts

### ISSUE THREAD

**Issue by carloslfu** [patrickmichalina/fusing-angular-cli#5]
Hi, @patrickmichalina great work. Would be useful to have a checklist or something in the README or in an issue for tracking progress, I would love to use this tool in production and contribute if needed.

**Comment by patrickmichalina** [comment]
@carloslfu will do! Still getting the v1 worked out, its not functional yet... Couple more weeks. Thanks :)

**Comment by patrickmichalina** [comment]
@carloslfu check it out [here](https://github.com/patrickmichalina/fusing-angular-cli/blob/master/ROADMAP.md)
